"""
Delivery Agent — generates DOCX file, then delivers via download link,
LMS upload, or email.
"""
import os
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from typing import Dict, Any
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import re

logger = logging.getLogger(__name__)

SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_EMAIL    = os.getenv("FROM_EMAIL", "asa@scholarassistant.ai")

OUTPUT_DIR = os.getenv("OUTPUT_DIR", "/tmp/asa-outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ─── DOCX Generator ───────────────────────────────────────────────────────────

def markdown_to_docx(essay_md: str, title: str, student_name: str,
                     module_code: str, assignment_id: str) -> str:
    """
    Convert markdown essay to a formatted DOCX file.
    Returns the path to the saved file.
    """
    doc = Document()

    # ── Page margins ──
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    section = doc.sections[0]
    section.top_margin    = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin   = Inches(1.25)
    section.right_margin  = Inches(1.25)

    # ── Cover page ──
    cover = doc.add_paragraph()
    cover.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cover.add_run(module_code.upper() if module_code else "ASSIGNMENT")
    r.bold = True; r.font.size = Pt(18)

    doc.add_paragraph()
    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    t.add_run(title).font.size = Pt(14)

    doc.add_paragraph()
    s = doc.add_paragraph()
    s.alignment = WD_ALIGN_PARAGRAPH.CENTER
    s.add_run(f"Student: {student_name}")
    doc.add_paragraph()
    s2 = doc.add_paragraph()
    s2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    s2.add_run(f"Generated by ASA v2 — Agentic Scholar Assistant")
    doc.add_page_break()

    # ── Parse and render markdown ──
    lines = essay_md.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        # H2 heading → Heading 1 in doc
        if line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=1)

        # H3 heading → Heading 2
        elif line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=2)

        # Bullet points (reference list lines)
        elif line.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(line[2:])

        # Code block
        elif line.startswith("```"):
            i += 1
            code_lines = []
            while i < len(lines) and not lines[i].startswith("```"):
                code_lines.append(lines[i])
                i += 1
            p = doc.add_paragraph()
            r = p.add_run("\n".join(code_lines))
            r.font.name = "Courier New"
            r.font.size = Pt(9)

        # Bold text in paragraph (handle **bold**)
        elif line.strip():
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            # Simple bold parsing
            parts = re.split(r'\*\*(.+?)\*\*', line)
            for idx, part in enumerate(parts):
                run = p.add_run(part)
                if idx % 2 == 1:  # odd indices are the bold parts
                    run.bold = True
                run.font.size = Pt(12)

        # Empty line → add spacing
        else:
            pass  # Don't add excessive blank paragraphs

        i += 1

    # ── Save ──
    safe_title = re.sub(r'[^\w\s-]', '', title)[:50].strip().replace(' ', '_')
    filename = f"{safe_title}_{assignment_id[:8]}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc.save(filepath)
    logger.info(f"DOCX saved: {filepath}")
    return filepath

# ─── Email Delivery ───────────────────────────────────────────────────────────

def deliver_email(docx_path: str, recipient_email: str, title: str, student_name: str) -> Dict[str, Any]:
    """Send the completed DOCX as an email attachment."""
    if not SMTP_USERNAME or not SMTP_PASSWORD:
        logger.warning("SMTP not configured — skipping email delivery")
        return {"status": "skipped", "reason": "SMTP not configured"}

    try:
        msg = MIMEMultipart()
        msg["From"]    = FROM_EMAIL
        msg["To"]      = recipient_email
        msg["Subject"] = f"Your ASA Assignment: {title}"

        body = f"""Dear {student_name},

Your assignment "{title}" has been completed by the Agentic Scholar Assistant (ASA v2).

Please find your assignment attached as a Word document (.docx).

Key information:
• The document includes in-text citations and a full reference list
• All sources are from peer-reviewed academic journals
• If you selected Professor Review, please allow up to 48 hours for annotations

If you have any questions, please contact support@scholarassistant.ai

Best regards,
The ASA Team
"""
        msg.attach(MIMEText(body, "plain"))

        # Attach DOCX
        with open(docx_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f"attachment; filename={os.path.basename(docx_path)}")
        msg.attach(part)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(FROM_EMAIL, recipient_email, msg.as_string())

        logger.info(f"Email sent to {recipient_email}")
        return {"status": "delivered", "recipient": recipient_email}

    except Exception as e:
        logger.error(f"Email delivery error: {e}")
        return {"status": "failed", "error": str(e)}

# ─── LMS Upload Delivery ──────────────────────────────────────────────────────

def deliver_lms(docx_path: str, lms_url: str, lms_username: str,
                lms_password: str, assignment_id: str) -> Dict[str, Any]:
    """
    Upload the DOCX to a Moodle LMS assignment using Playwright.
    Uses the proven repository API approach from ASA v1.
    """
    try:
        from playwright.sync_api import sync_playwright
        import base64

        file_buffer = open(docx_path, "rb").read()
        file_base64 = base64.b64encode(file_buffer).decode()
        filename    = os.path.basename(docx_path)

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page    = browser.new_page(viewport={"width": 1440, "height": 900})
            page.set_default_timeout(30000)

            # Login
            lms_root = lms_url.split("/mod/")[0] if "/mod/" in lms_url else lms_url.rstrip("/")
            page.goto(f"{lms_root}/login/index.php")
            page.fill("#username", lms_username)
            page.fill("#password", lms_password)
            page.click("#loginbtn")
            page.wait_for_timeout(3000)
            if "login" in page.url:
                raise Exception("LMS login failed")

            # Navigate to edit submission
            edit_url = lms_url.replace("view.php", "view.php") + "&action=editsubmission"
            page.goto(edit_url)
            page.wait_for_load_state("domcontentloaded")
            page.wait_for_timeout(2000)

            # Extract session values
            page_data = page.evaluate("""() => {
                const hidden = {};
                document.querySelectorAll('input[type=hidden]').forEach(el => { hidden[el.name] = el.value; });
                const mcfg = window.M && window.M.cfg ? window.M.cfg : {};
                const fmEl = document.querySelector('[id^="filemanager-"]');
                const clientId = fmEl ? fmEl.id.replace('filemanager-', '') : null;
                return { hidden, sesskey: mcfg.sesskey || hidden.sesskey, itemId: hidden.files_filemanager, ctxId: mcfg.contextid, clientId };
            }""")

            sesskey   = page_data.get("sesskey")
            item_id   = page_data.get("itemId")
            ctx_id    = page_data.get("ctxId")
            client_id = page_data.get("clientId")

            if not sesskey or not item_id:
                raise Exception("Could not extract Moodle session data")

            # Upload via repository API (repo_id=4 = Upload a file)
            upload_result = page.evaluate("""async ({base64, fileName, sesskey, itemId, ctxId, clientId}) => {
                const byteChars = atob(base64);
                const bytes = new Uint8Array(byteChars.length);
                for (let i = 0; i < byteChars.length; i++) bytes[i] = byteChars.charCodeAt(i);
                const blob = new Blob([bytes], {type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
                const fd = new FormData();
                fd.append('action', 'upload'); fd.append('sesskey', sesskey);
                fd.append('client_id', clientId || ''); fd.append('maxbytes', '5242880');
                fd.append('areamaxbytes', '-1'); fd.append('ctx_id', String(ctxId));
                fd.append('component', 'assignsubmission_file'); fd.append('filearea', 'draft');
                fd.append('itemid', String(itemId)); fd.append('filepath', '/');
                fd.append('repo_id', '4');
                fd.append('repo_upload_file', blob, fileName);
                fd.append('savepath', '/');
                const resp = await fetch('/repository/repository_ajax.php?action=upload', {method: 'POST', body: fd});
                return {status: resp.status, body: await resp.text()};
            }""", {"base64": file_base64, "fileName": filename, "sesskey": sesskey,
                   "itemId": item_id, "ctxId": ctx_id, "clientId": client_id})

            if '"error"' in str(upload_result.get("body", "")):
                raise Exception(f"Upload failed: {upload_result['body'][:200]}")

            # Submit form
            page.evaluate("""() => {
                const btn = document.querySelector('input[name="submitbutton"]') || document.querySelector('#id_submitbutton');
                if (btn) { btn.disabled = false; btn.click(); }
            }""")
            page.wait_for_load_state("domcontentloaded")
            page.wait_for_timeout(3000)

            # Handle "Submit for grading" confirmation
            submit_btn = page.locator('input[name="submitbutton"]').first()
            if submit_btn.count() > 0:
                submit_btn.click(force=True)
                page.wait_for_timeout(2000)
                ok_btn = page.locator('button:has-text("Continue")').first()
                if ok_btn.count() > 0:
                    ok_btn.click(force=True)

            browser.close()
            return {"status": "delivered", "method": "lms_upload", "url": lms_url}

    except Exception as e:
        logger.error(f"LMS upload error: {e}")
        return {"status": "failed", "error": str(e)}

# ─── Unified Delivery Orchestrator ────────────────────────────────────────────

def run_delivery_pipeline(
    essay_md: str,
    title: str,
    student_name: str,
    module_code: str,
    assignment_id: str,
    delivery_method: str,
    delivery_email: str = None,
    lms_url: str = None,
    lms_username: str = None,
    lms_password: str = None,
) -> Dict[str, Any]:
    """
    Full delivery pipeline:
    1. Generate DOCX
    2. Deliver via chosen method (download link / email / LMS upload)
    """
    logger.info(f"Delivery pipeline: method={delivery_method}")

    # Step 1: Generate DOCX
    docx_path = markdown_to_docx(essay_md, title, student_name, module_code, assignment_id)

    result = {
        "docx_path": docx_path,
        "delivery_method": delivery_method,
        "status": "pending",
    }

    # Step 2: Deliver
    if delivery_method == "email" and delivery_email:
        delivery_result = deliver_email(docx_path, delivery_email, title, student_name)
        result.update(delivery_result)

    elif delivery_method == "lms_upload" and lms_url and lms_username and lms_password:
        delivery_result = deliver_lms(docx_path, lms_url, lms_username, lms_password, assignment_id)
        result.update(delivery_result)

    else:  # download
        result["status"] = "ready_for_download"
        result["download_url"] = f"/api/v1/assignments/{assignment_id}/download"

    return result
